/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "relative",
    "inline-block",
    "text-left",
    "text-white",
    "bg-blue-700",
    "hover:bg-blue-800",
    "focus:ring-4",
    "focus:outline-none",
    "focus:ring-blue-300",
    "font-medium",
    "rounded-lg",
    "text-sm",
    "px-2.5",
    "md:px-5",
    "py-2.5",
    "text-center",
    "inline-flex",
    "items-center",
    "dark:bg-blue-600",
    "dark:hover:bg-blue-700",
    "dark:focus:ring-blue-800",
    "md:hidden",
    "hidden",
    "md:block",
    "w-2.5",
    "h-2.5",
    "ms-3",
    "absolute",
    "z-10",
    "bg-white",
    "divide-y",
    "divide-gray-100",
    "rounded-lg",
    "shadow",
    "md:w-44",
    "dark:bg-gray-700",
    "py-2",
    "text-sm",
    "text-gray-700",
    "dark:text-gray-200",
    "block",
    "px-4",
    "py-2",
    "hover:bg-gray-100",
    "dark:hover:bg-gray-600",
    "dark:hover:text-white",
    "w-full",
    "text-left",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        "custom-background": "#212131",
      },
    },
  },
  plugins: [],
};
